### ISSUE TITLE
Autoria da música

### ISSUE THREAD

**Issue by eduardomarossi** [decoejz/APS1embarcados#3]
https://github.com/decoejz/APS1embarcados/blob/b2b2de36c6dfa3c1aee475db3143a41296024c42/apsBuzzer/src/main.c#L115

Faltou indicar o autor/editora e nome da música para dar direitos ao artista.

**Comment by eduardomarossi** [comment]
Isto também vale para as outras músicas

**Comment by decoejz** [comment]
No arquivo apsBuzzer/src/musicas.h, no começo de cada música, esta a autoria de quem a escreveu.
